DROP DATABASE IF EXISTS tech_blog;
CREATE DATABASE tech_blog;

-- DROP TABLE IF EXISTS comments;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS posts;

-- CREATE TABLE comments;
-- CREATE TABLE users;
-- CREATE TABLE posts;